const SEARCH = 'SEARCH'
const IS_LOADING = 'IS_LOADING'
const RESET_SEARCH = 'RESET_SEARCH'
const HIDE_LOADING = 'HIDE_LOADING'
const CHANGE_SEARCH = 'CHANGE_SEARCH'
const ADD_FAVOURITES = 'ADD_FAVOURITES'
const REMOVE_FAVOURITES = 'REMOVE_FAVOURITES'
const ADD_DATA = 'ADD_DATA'
const ADD_HANDLED_DATA = 'ADD_HANDLED_DATA'
const NO_RESULT = 'NO_RESULT'

export default {
    SEARCH,
    IS_LOADING,
    RESET_SEARCH,
    HIDE_LOADING,
    CHANGE_SEARCH,
    ADD_FAVOURITES,
    REMOVE_FAVOURITES,
    ADD_HANDLED_DATA,
    ADD_DATA,
    NO_RESULT
}